services:
  rabbitmq:
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"  # Порт для управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      MQ_HOST: localhost
      MQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      MQ_ROUTING_KEY_DLQ: rpc_dlq
      MQ_ROUTING_KEY_RPC_QUEUE: rpc_user_service_queue
      MQ_ROUTING_KEY_RPC_RESPONSE_QUEUE: rpc_user_service_response_queue
      MQ_MESSAGE_TTL: 6000

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: