services:
  rabbitmq:
    build: .
    ports:
      - "5672:5672"  # Порт для RabbitMQ
      - "15672:15672"  # Порт для управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      MQ_HOST: localhost
      MQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      MQ_ROUTING_KEY_DLQ: rpc_dlq
      # MQ_ROUTING_KEY_RPC_QUEUE: rpc_queue
      # MQ_ROUTING_KEY_RPC_RESPONSE_QUEUE: rpc_response_queue
      MQ_ROUTING_KEY_RPC_MOVIE_QUEUE: rpc_movie_queue
      MQ_ROUTING_KEY_RPC_MOVIE_RESPONSE_QUEUE: rpc_movie_response_queue
      MQ_ROUTING_KEY_RPC_USER_QUEUE: rpc_user_queue
      MQ_ROUTING_KEY_RPC_USER_RESPONSE_QUEUE: rpc_user_response_queue

      MQ_MESSAGE_TTL: 6000
      
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Сохраняем данные RabbitMQ

volumes:
  rabbitmq_data:  # Определяем volume
